name: JACOCO

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      narayanaRepo:
        description: 'Repo to clone for Narayana'
        required: true
        default: 'marcosgopen/narayana'
        type: 'string'
      narayanaBranch:
        description: 'Branch to use from narayana'
        required: true
        default: 'main'
        type: 'string'

jobs:
  core-test:
    name: JACOCO test with JDK ${{ matrix.java-version }}
    timeout-minutes: 120
    strategy:
      matrix:
        java-version: [ 17, 21 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ inputs.narayanaRepo }}
          ref: ${{ inputs.narayanaBranch }}

      - uses: actions/setup-java@v5
        name: Set up JDK ${{ matrix.java-version }}
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: JACOCO test
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          WORKSPACE=$PWD PROFILE=JACOCO ./scripts/hudson/narayana.sh
        env:
          LRA_TCK_TIMEOUT_FACTOR: 1

      - uses: actions/upload-artifact@v5
        if: always()
        with:
          name: core-logs-jdk${{ matrix.java-version }}
          path: |
            jboss-as/dist/target/wildfly-*/standalone/log/
            **/ObjectStore*/**
            **/tx-object-store/**
            **/*tx-object-store.zip
            **/target/*failsafe-reports*/**
            **/target/site/**
            **/*.exec
            *.csv
          if-no-files-found: error
